//////////////////////////////////////////////////////////////////////////////////////////////////
//
//  Copyright © GISExpress 2015-2017. All Rights Reserved.
//  
//  GISExpress .NET API and Component Library
//  
//  The entire contents of this file is protected by local and International Copyright Laws.
//  Unauthorized reproduction, reverse-engineering, and distribution of all or any portion of
//  the code contained in this file is strictly prohibited and may result in severe civil and 
//  criminal penalties and will be prosecuted to the maximum extent possible under the law.
//  
//  RESTRICTIONS
//  
//  THIS SOURCE CODE AND ALL RESULTING INTERMEDIATE FILES ARE CONFIDENTIAL AND PROPRIETARY TRADE SECRETS OF GISExpress
//  THE REGISTERED DEVELOPER IS LICENSED TO DISTRIBUTE THE PRODUCT AND ALL ACCOMPANYING .NET COMPONENTS AS PART OF AN EXECUTABLE PROGRAM ONLY.
//  
//  THE SOURCE CODE CONTAINED WITHIN THIS FILE AND ALL RELATED FILES OR ANY PORTION OF ITS CONTENTS SHALL AT NO TIME BE
//  COPIED, TRANSFERRED, SOLD, DISTRIBUTED, OR OTHERWISE MADE AVAILABLE TO OTHER INDIVIDUALS WITHOUT EXPRESS WRITTEN CONSENT
//  AND PERMISSION FROM GISExpress
//  
//  CONSULT THE END USER LICENSE AGREEMENT FOR INFORMATION ON ADDITIONAL RESTRICTIONS.
//  
//  Warning: This content was generated by GISExpress tools.
//  Changes to this content may cause incorrect behavior and will be lost if the content is regenerated.
//
///////////////////////////////////////////////////////////////////////////////////////////////////

using System.Geometries;

namespace System.Data.Dxf
{
    internal class AcDbLine : AcDbObject
    {
        public AcDbLine()
        {
            StartPoint = GeometryFactory.CreateCoordinate();
            EndPoint = GeometryFactory.CreateCoordinate();
        }

        public ICoordinate StartPoint
        {
            get;
            set;
        }

        public ICoordinate EndPoint
        {
            get;
            set;
        }

        public float Thickness
        {
            get;
            set;
        }

        public override IGeometry GetGeometry()
        {
            if (StartPoint.IsEmpty() || EndPoint.IsEmpty() || StartPoint.IsEquivalent(EndPoint))
            {
                return default(IGeometry);
            }

            return GeometryFactory.CreateLineString(StartPoint, EndPoint);
        }

        protected override void OnRead(DxfReader reader)
        {
            switch (reader.GroupCode)
            {
                case 10:
                    StartPoint.X = reader.GetDouble();
                    break;
                case 20:
                    StartPoint.Y = reader.GetDouble();
                    break;
                case 30:
                    StartPoint.Z = reader.GetDouble();
                    break;
                case 11:
                    EndPoint.X = reader.GetDouble();
                    break;
                case 21:
                    EndPoint.Y = reader.GetDouble();
                    break;
                case 31:
                    EndPoint.Z = reader.GetDouble();
                    break;
                case 39:
                    Thickness = reader.GetSingle();
                    break;
            }

            base.OnRead(reader);
        }
    }
}
